version: '3.3'

services:
    db:
      image: mysql:$mysql_version
      volumes:
        - db_data:/var/lib/mysql
      env_file: .env
      environment:
        - MYSQL_ROOT_PASSWORD=$mysql_root_pass
        - MYSQL_DATABASE=$mysql_db
        - MYSQL_USER=$mysql_user
        - MYSQL_PASSWORD=$mysql_pass
      restart: always
      networks:
        - wpnetwork

    wordpress:
      depends_on:
        - db
      image: wordpress:$wp_version
      ports:
        - "8001:80"
      restart: always
      env_file: .env
      environment:
        - WORDPRESS_DB_HOST=db:3306
        - WORDPRESS_DB_USER=$wp_db_user
        - WORDPRESS_DB_PASSWORD=$wp_db_pass
        - WORDPRESS_DB_NAME=$wp_db_name
      networks:
        - wpnetwork

volumes:
  db_data:

networks:
  wpnetwork:
