version: '3.3'

services:

    nginx:
      image: nginx:alpine
      ports:
        - 80:80
        - 443:443
      volumes:
        - html:/var/www/html
        - ./ssl:/var/www/ssl
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - wpnetwork
      depends_on:
         - php

    php:
      image: wordpress:5.4.1-php7.2-fpm-alpine
      volumes:
        - html:/var/www/html
      env_file: .env
      environment:
        - WORDPRESS_DB_HOST=db:3306
        - WORDPRESS_DB_USER=$wp_db_user
        - WORDPRESS_DB_PASSWORD=$wp_db_pass
        - WORDPRESS_DB_NAME=$wp_db_name
      networks:
        - wpnetwork
      depends_on:
         - db

    db:
      image: mysql:$mysql_version
      volumes:
        - db_data:/var/lib/mysql
      env_file: .env
      environment:
        - MYSQL_ROOT_PASSWORD=$mysql_root_pass
        - MYSQL_DATABASE=$mysql_db
        - MYSQL_USER=$mysql_user
        - MYSQL_PASSWORD=$mysql_pass
      restart: always
      networks:
        - wpnetwork

volumes:
  html:
  db_data:

networks:
  wpnetwork: